name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '30 14 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -r linux-x64 -c Release /p:PublishSingleFile=true --self-contained
    - name: Run
      run: /home/runner/work/OptechX.NewsReader/OptechX.NewsReader/bin/Release/net7.0/linux-x64/publish/OptechX.NewsReader --apiKey ${{ secrets.NEWSAPI_APIKEY }} --country us --category technology --pageSize 20
